Patch git-filter-branch to split state file
A single file is now > 100M which is too big to push to the state repository.

diff --git a/scripts/git-filter-branch b/scripts/git-filter-branch
--- a/scripts/git-filter-branch
+++ b/scripts/git-filter-branch
@@ -289,21 +289,25 @@ export GIT_INDEX_FILE
 # map old->new commit ids for rewriting parents
 mkdir ../map || die "Could not create map/ directory"
 
+state_prefixes="0 1 2 3 4 5 6 7 8 9 a b c d e f"
+
 if test -n "$state_branch"
 then
 	state_commit=$(git rev-parse --no-flags --revs-only "$state_branch")
 	if test -n "$state_commit"
 	then
 		echo "Populating map from $state_branch ($state_commit)" 1>&2
-		perl -e'open(MAP, "-|", "git show $ARGV[0]:filter.map") or die;
-			while (<MAP>) {
-				m/(.*):(.*)/ or die;
-				open F, ">../map/$1" or die;
-				print F "$2" or die;
-				close(F) or die;
-			}
-			close(MAP) or die;' "$state_commit" \
-				|| die "Unable to load state from $state_branch:filter.map"
+		for prefix in $state_prefixes ; do
+			perl -e'open(MAP, "-|", "git show $ARGV[0]:$ARGV[1]") or die;
+				while (<MAP>) {
+					m/(.*):(.*)/ or die;
+					open F, ">../map/$1" or die;
+					print F "$2" or die;
+					close(F) or die;
+				}
+				close(MAP) or die;' "$state_commit" "filter_${prefix}.map" \
+					|| die "Unable to load state from $state_branch:filter_${prefix}.map"
+		done
 	else
 		echo "Branch $state_branch does not exist. Will create" 1>&2
 	fi
@@ -632,17 +636,22 @@ test -z "$ORIG_GIT_COMMITTER_DATE" || {
 if test -n "$state_branch"
 then
 	echo "Saving rewrite state to $state_branch" 1>&2
-	state_blob=$(
-		perl -e'opendir D, "../map" or die;
-			open H, "|-", "git hash-object -w --stdin" or die;
-			foreach (sort readdir(D)) {
-				next if m/^\.\.?$/;
-				open F, "<../map/$_" or die;
-				chomp($f = <F>);
-				print H "$_:$f\n" or die;
-			}
-			close(H) or die;' || die "Unable to save state")
-	state_tree=$(printf '100644 blob %s\tfilter.map\n' "$state_blob" | git mktree)
+	for prefix in $state_prefixes ; do
+		state_blob=$(
+			perl -e'opendir D, "../map" or die;
+				open H, "|-", "git hash-object -w --stdin" or die;
+				foreach (sort readdir(D)) {
+					next if m/^\.\.?$/;
+					next unless m/^$ARGV[0]/;
+					open F, "<../map/$_" or die;
+					chomp($f = <F>);
+					print H "$_:$f\n" or die;
+				}
+				close(H) or die;' "$prefix" || die "Unable to save state")
+		printf '100644 blob %s\tfilter_%s.map\n' "$state_blob" "$prefix" >> $tempdir/state-branch-tree
+	done
+	state_tree=$(cat $tempdir/state-branch-tree | git mktree)
+
 	if test -n "$state_commit"
 	then
 		state_commit=$(echo "Sync" | git commit-tree "$state_tree" -p "$state_commit")
